# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 10:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 6, 23, 10, 18, 57, 979778, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
