# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_join_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='name',
        ),
        migrations.AddField(
            model_name='join',
            name='ip_address',
            field=models.CharField(default='ABC', max_length=120),
        ),
    ]
